apiVersion: v1
kind: Service
metadata:
  name: mysvcnodeport
spec:
  ports:
    - name: web-nginx
      port: 9001
      targetPort: 80
      nodePort: 32080
    - name: web-mtools
      port: 9002
      targetPort: 8080
      nodePort: 31280
  selector:
    app: myapp1.4
  type: NodePort