apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-deployment
  labels:
    app: main
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command: [ 'sh', '-c', 'while true; do echo Netology! >> /sasha/logoutput.txt; sleep 5; done']
        volumeMounts:
        - mountPath: /sasha
          name: varlog   
      
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
          - mountPath: /sasha
            name: varlog
      volumes:
      - name: varlog
        persistentVolumeClaim:
          claimName: pvc-nfs